# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Simple test function for long long vectors
#'
#' @title A simple test function for long long vectors
#' @param x A vector of long long integers
#' @return A double vector
#' @author Dirk Eddelbuettel
longlongFun <- function(x) {
    .Call('RcppLongLong_longlongFun', PACKAGE = 'RcppLongLong', x)
}

#' Simple test function for long vectors
#'
#' @title A simple test function for long vectors
#' @param x A vector of long long integers
#' @return A double vector
#' @author Dirk Eddelbuettel
longFun <- function(x) {
    .Call('RcppLongLong_longFun', PACKAGE = 'RcppLongLong', x)
}

